spring:
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.99.100
    port: 6379
  cloud:
    stream:
      bindings:
        myInput:
          destination: myStream
          group: order
          content-type: application/json
        myOutput:
          destination: myStream
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://127.0.0.1:3306/springcloud?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
  jpa:
      show-sql: true
      database: mysql
      hibernate:
        ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
